### ISSUE TITLE
Register with init = itself doesn't run

### ISSUE THREAD

**Issue by grebe** [freechipsproject/firrtl#1516]
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [x] Did you specify relevant external information?

### What is the current behavior?
The following circuit doesn't compile for me. It doesn't crash, it just hangs. I assume the problem is `reset => (reset, a)`

```
  module A :
    input clock : Clock
    input reset : AsyncReset
    input in : UInt<12>
    output out : UInt<10>
  
    reg a : UInt<10>, clock with :
      reset => (reset, a)
    out <= UInt<5>("h15")
```

### What is the expected behavior?
This should be an error. I could also see an argument that this should elide the reset/initialization.

### Your environment
Mac OS X.

Firrtl 1a03e6356e451136d522d5a9acba374dd8972b24

**Comment by albert-magyar** [comment]
> This should be an error. I could also see an argument that this should elide the reset/initialization.

Self-initialization is currently used as part an idiom for "no reset," but this generally been paired with a `reset` is hardwired to zero.

I would say there is still some question about whether this should work when paired with a real async reset, but there is currently a test case that suggests that it should just resolve to "no reset."

Regardless, the underlying problem is that `CheckResets` seems to have an infinite recursion issue when encountering the self-referential loop. Since it uses a `@tailrec` annotation on the function in question, this just hangs.

I added a fix for this in #1525 -- hopefully @jackkoenig can chime in, since he is the async-reset czar. If the desired behavior is to add stricter checks that would make this case error, that would be a one-line change to #1525.
