### ISSUE TITLE
Generic Annotation

### ISSUE THREAD

**Issue by shunshou** [freechipsproject/firrtl#475]
I think we talked about this earlier, but I'm just going to file an issue to track -- I'd like to have some generic annotation that applies to the entire circuit. That way, I don't need to use my BlackBoxSourceHelper hack to get stuff like targetDir name. (Or input config file location).

**Comment by jackkoenig** [comment]
Thanks for tracking this. I actually have a related thing in my PR here: https://github.com/ucb-bar/firrtl/blob/9a6a2a05abca97a4ec178112083a036712146d03/src/main/scala/firrtl/annotations/Named.scala#L19

But that only solves the "Named" part. I think the way of dealing with the target transform is to use `classOf[Transform]` (instead of the class of a specific transform). However, we need to change [`getMyAnnotations`](https://github.com/ucb-bar/firrtl/blob/master/src/main/scala/firrtl/Compiler.scala#L106) to return these annotations as well.

**Comment by jackkoenig** [comment]
Will be fixed by annotations refactor
