### ISSUE TITLE
spec: memory syntax differs from chisel3 reality

### ISSUE THREAD

**Issue by sorear** [freechipsproject/firrtl#623]
Chisel3 represents memories using the `smem` and `cmem` keywords, e.g. https://github.com/freechipsproject/chisel3/blob/aaee58d374dc3f3a088856da13a6a59ecffb2cac/src/main/scala/chisel3/internal/firrtl/Emitter.scala#L58

The FIRRTL spec does not mention  smem or cmem; instead it defines a single `mem` keyword with a `read-latency` that identifies combinational or sequential behavior: https://github.com/freechipsproject/firrtl/blob/b60c31806e9220d63ac2dae98ef4b54c37122491/spec/spec.tex#L755-L766

**Comment by edwardcwang** [comment]
In this case, it seems that the spec might be out of date with the current implementation of FIRRTL.

**Comment by jackkoenig** [comment]
This is due to a poorly documented mismatch between Chisel IR (Chirrtl) and Firrtl. The purpose of Chirrtl was to help a simple lean Chisel3 frontend use it's looser memory notions with Firrtl. The first thing that the Firrtl compiler does is convert `cmem` and `smem` to `mem` (ie. we run the Chirrtl -> High Firrtl transform).

Solution: Chirrtl as a construct should be moved into chisel3 so that only legal Firrtl is emitted. Since chisel3 depends on firrtl this shouldn't be too difficult to do.

**Comment by edwardcwang** [comment]
Or perhaps we should document chirrtl ("lean Chisel3 frontend use it's looser memory notions with Firrtl")?

**Comment by azidar** [comment]
This will be fixed with new resolution of #702

**Comment by albert-magyar** [comment]
To be fixed in #1210
