### ISSUE TITLE
latest FIRRTL generates incorrect code in rocket-chip 

### ISSUE THREAD

**Issue by mwachs5** [freechipsproject/firrtl#705]
See https://github.com/freechipsproject/rocket-chip/issues/1160

**Comment by mwachs5** [comment]
(also, how come I didn't get the fancy template for filing my issue? How is that flow supposed to work)?

**Comment by jackkoenig** [comment]
Because I forgot to approve and merge #699. Anyway I've narrowed down the bug, fix coming soon.

For those interested, if you don't invalidate input ports of a submodule and yet you only connect to them conditionally, it drops most of the conditional connections and picks one (I think the last one). This hasn't come up because Chisel was invalidating everything always, but it doesn't anymore.
