### ISSUE TITLE
Don't Emit Emitter Annotations nor Deleted Annotations by default

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/firrtl#793]
Emitter annotations are just massive and redundant. I also think Deleted Annotations clutter everything up, perhaps there could be an option?

* **Type of issue**
  - [ ] Bug report
  - [x] Feature request
  - [ ] Other enhancement

* **What is the use case for changing the behavior?**

Make looking at the emitted annotations actually useful, especially if trying to chain invocations of firrtl together.

* **Impact**
  - [ ] no functional change
  - [ ] API addition (no impact on existing code)
  - [x] API modification (I doubt anyone is relying on this but 🤷‍♀️)
  - [ ] unknown

* **Development Phase**
  - [x] request
  - [ ] proposal

**Comment by seldridge** [comment]
@jackkoenig, I think I'm in agreement with this. Likely, there should be some flag (annotation) that turns this on or off.

Related to this, `DeletedAnnotation`s aren't even emitted correctly. I was doing some tests and realized that they can't be deserialized after serialization (due to them not being serialized correctly). E.g., the following `DeletedAnnotation` should include the `class` of the deleted annotation, but it doesn't. Fix should be trivial, but likely a case for just preventing emission.
```json
  {
    "class":"firrtl.annotations.DeletedAnnotation",
    "xFormName":"AddCircuit$",
    "anno":{
      "file":"test_run_dir/FirrtlStageSpec/implict-annotation-file/Top.fir"
    }
  }
```
