### ISSUE TITLE
MuxCase invalid inference

### ISSUE THREAD

**Issue by tampler** [freechipsproject/firrtl#884]
Hello

**MuxCase** fails on inference. It tries to infer a string type, whereas UInt is supposed

[error]  found   : chisel3.core.UInt
[error]  required: String
[error]     r1 := MuxCase(r1, Array( io.clr -> 0.U, io.ena -> r1 + 1.U))
[error]                                                                                             ^

Both MuxCase options fail to compile with the same message. Nested Mux works fine
Chisel 3.1.2, Scala 2.12.6

```scala
class Counter(size: Int) extends Module {
  val io = IO(new Bundle {
    val out = Output(UInt(size.W))
    val ena  = Input (Bool())
    val clr  = Input (Bool())
  })

  val r1 = RegInit (0.U(size.W))

  when (reset.toBool) {
    r1 := 0.U   
  }
  .otherwise {
    //r1 := Mux(io.clr, 0.U, Mux(io.ena, r1 + 1.U, r1))
    //r1 := MuxCase(r1, Array( (io.clr === true.B) -> 0.U, (io.ena === true.B ) -> r1 + 1.U))
    r1 := MuxCase(r1, Array( io.clr -> 0.U, io.ena -> r1 + 1.U)
  }  
  io.out := r1
}

```

**Comment by jackkoenig** [comment]
So this one comes from Scala operator precedence. As in most languages, `+` and `-` have the same precedence. However, because in Scala symbols are allowed in function names, precedence comes from the *first character in the function name*. Concretely, `->` and `+` have the same precedence.

Thus, `io.ena -> r1 + 1.U` is the same as `(io.ena -> r1) + 1.U` when obviously what you're really looking for is `io.ena -> (r1 + 1.U)`. You can resolve this by adding the parentheses as shown, or you could use the alternative tuple construction syntax: `(io.ena, r1 + 1.U)`

Hope that makes sense!

**Comment by tampler** [comment]
Thank you, Jack, that did a trick. Both options do compile as expected

I started to love Scala with Rocket and RISC-V, but there's a steep learning/practice curve to get the min required skill to be effective in RTL design with Chisel3 for complex projects
