### ISSUE TITLE
Invalid Dead Code Elimination operation

### ISSUE THREAD

**Issue by tampler** [freechipsproject/firrtl#914]
How to turn off Dead Code Elimination in FIRRTL during sbt compile? I suspect DCE to give a false positive, since I see my code in the *.fir, which gets trimmed in the *.v file

**Comment by grebe** [comment]
I think [dontTouch](https://github.com/freechipsproject/chisel3/blob/e564fff139768e6a232d118ec7155ecf080f1bc4/chiselFrontend/src/main/scala/chisel3/core/Annotation.scala#L75) is what you want

**Comment by edwardcwang** [comment]
`dontTouch` works on signals. See https://chisel.eecs.berkeley.edu/api/latest/chisel3/core/dontTouch$.html

**Comment by jackkoenig** [comment]
```
[error] inferred type arguments [Seq[chisel3.core.SyncReadMem[A]]] do not conform to method apply's type parameter bounds [T <: chisel3.core.Data]
```
Means that you can only call `dontTouch` on a subtype of `Data`. Mems do not extend `Data`, but the output of reading does and can serve as a proxy for dontTouching the memory. The simplest thing to do here would probably just `dontTouch` your whole `io` since this is effectively just wrapping up the memory, try:

```scala
dontTouch(io)
```

**Comment by tampler** [comment]
@jackkoenig This worked fine for me, thank you. 
Your solution prevents DCE from trimming up IO, but I still have architectural issues, which are not related to this issue. Thanks for your help!
